name: Publish

on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "true"
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x
            - name: Build
              run: deno task release
            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: |
                    ./src/datex-core/datex_core_js.internal.js
                    ./src/datex-core/datex_core_js.wasm
                  retention-days: 5

    publish-jsr:
        runs-on: ubuntu-latest
        needs: build
        name: Publish to JSR
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "true"
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: ./src/datex-core
            # publish to JSR
            - name: Publish package
              run: npx jsr publish
    publish-npm:
        runs-on: ubuntu-latest
        needs: build
        name: Publish to NPM
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "true"
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: ./src/datex-core
            - name: Install Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - uses: actions/setup-node@v4
              with:
                  node-version: "24.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Build for NPM
              run: deno task build-npm

            - name: Publish to NPM
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: cd npm && npm publish --provenance --access public
