on:
    release:
        types: [published]
jobs:
    publish:
        runs-on: ubuntu-latest
        name: Publish
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4

            # publish to JSR
            - name: Publish package
              run: npx jsr publish
